# Generated by Django 2.1.5 on 2019-02-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mentor', models.CharField(max_length=255)),
                ('testimoni', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=300)),
                ('foto_mentor', models.ImageField(upload_to='upload')),
            ],
        ),
    ]
