# Generated by Django 2.1.5 on 2019-02-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentee',
            new_name='Mentor',
        ),
    ]
