# Generated by Django 2.1.5 on 2019-02-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0002_auto_20190213_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='foto_mentor',
            field=models.ImageField(upload_to='mentor'),
        ),
    ]
