# Generated by Django 2.1.5 on 2019-02-13 02:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi_post', models.CharField(max_length=3000)),
                ('created_at', models.DateField(default=datetime.datetime(2019, 2, 13, 2, 8, 48, 156583, tzinfo=utc))),
                ('foto', models.ImageField(upload_to='post')),
            ],
        ),
    ]
