# Generated by Django 2.1.5 on 2019-02-13 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 2, 10, 11, 317139, tzinfo=utc)),
        ),
    ]
