# Generated by Django 2.1.5 on 2019-02-13 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190213_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 6, 2, 4, 799608, tzinfo=utc)),
        ),
    ]
