# Generated by Django 2.1.5 on 2019-02-13 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20190213_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 10, 53, 10, 511397, tzinfo=utc)),
        ),
    ]
