# Generated by Django 2.1.5 on 2019-02-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mentee', models.CharField(max_length=255)),
                ('testimoni', models.CharField(max_length=300)),
            ],
        ),
    ]
