# Generated by Django 2.1.5 on 2019-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='foto_mentee',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
