# Generated by Django 2.1.5 on 2019-02-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentee', '0002_mentee_foto_mentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='foto_mentee',
            field=models.ImageField(upload_to=''),
        ),
    ]
