# Generated by Django 2.1.5 on 2019-02-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentee', '0003_auto_20190212_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='foto_mentee',
            field=models.CharField(max_length=300),
        ),
    ]
